---
# vars file for basic packages
java_repository: "ppa:openjdk-r/ppa"
java_install: "openjdk-11-jdk"
db_repo_config: 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list'
db_repo: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"
db_install: "postgresql-13"